a1/a1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include



urlpatterns = [
    path('admin/', admin.site.urls),
    url('a1/',include('booktest.urls'),name='booktest'),
]

a1/booktest/urls.py
from django.conf.urls import url
from . import views


app_name = 'booktest'


urlpatterns = [
    url(r'^list/$',views.list,name='list'),
    url(r'^index/$', views.index,name='index'),
    url(r'^xq/(\d+)/$', views.xq,name='xq'),


    url(r'^deletebook/(\d+)/$',views.deletebook,name='deletebook'),
    url(r'^addbook/$',views.addbook,name='addbook'),
    url(r'upbook',views.upbook,name='upbook'),



    url(r'^deletehero/(\d+)/$',views.deletehero,name='deletehero'),
    url(r'^addhero/(\d+)/$',views.addhero,name='addhero'),
    url(r'^uphero/(\d+)/$',views.uphero,name='uphero'),

]

a1/booktest/models.py
from django.db import models

# Create your models here.


GENDER = (("man",'男'),('women','女'))

class aaa(models.Model):

    title = models.CharField(max_length=30,verbose_name='书名')

    pub_date = models.DateTimeField(auto_now_add=True,verbose_name='日期')

    def __str__(self):
        return self.title


class bbb(models.Model):

    name = models.CharField(max_length=30,verbose_name='角色名')

    # gender = models.BooleanField(default=True,verbose_name='性别')

    gender = models.CharField(max_length=10,choices=GENDER,verbose_name='性别')

    skill = models.CharField(max_length=50,null=True,verbose_name='绝招')

    boot_id = models.ForeignKey(aaa,on_delete=models.CASCADE,verbose_name='书')

    def __str__(self):
        return self.name

a1/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import aaa,bbb

# Create your views here.

def index(request):

    return render(request,'booktest/shouye.html',{})

    # temp = loader.get_template('booktest/shouye.html')
    #
    # xur =temp.render({})
    #
    # return HttpResponse(xur)

    # return HttpResponse('首页')


def list(request):

    aa = aaa.objects.all()
    # print(aa)


    temp = loader.get_template('booktest/list.html')

    xur = temp.render({'aa':aa})

    return HttpResponse(xur)

def xq(request,id):
    try:
        bb = aaa.objects.get(pk=id)
        # print(bb)

    except Exception as e:
        return HttpResponse('没有这本书')

    temp = loader.get_template('booktest/xiangqing.html')

    xur = temp.render({'bb': bb})

    return HttpResponse(xur)

def deletebook(request,id):

    aaa.objects.get(pk=id).delete()


    return HttpResponseRedirect('/a1/list')


def deletehero(request,id):

    print(id)

    ccc = bbb.objects.get(pk=id)
    cc = ccc.boot_id.id
    ccc.delete()

    return HttpResponseRedirect('/a1/xq/%s/'%(cc,))


def addhero(request,id):
    if request.method =='GET':
        bb = bbb.objects.get(pk=id)
        bb1 = bb.boot_id
        return render(request, 'booktest/addhero.html', {'book': bb1, 'bookid': id})
    elif request.method =='POST':
        bbbb = bbb.objects.get(pk=id)
        print(id)
        hero = bbb()
        hero.name = request.POST['username']
        hero.gender = request.POST['sex']
        hero.skill = request.POST['skill']
        hero.boot_id = bbbb.boot_id
        hero.save()
        return HttpResponseRedirect('/a1/xq/%s'%(bbbb.boot_id.id))


def addbook(request):
    if request.method == 'GET':
        aa = aaa.objects.all()
        return render(request, 'booktest/addbook.html')

    elif request.method == 'POST':
        book = aaa()
        book.title = request.POST['bookname']
        book.pub_date = request.POST['time']
        book.save()
        return HttpResponseRedirect('/a1/list/')


def upbook(request):
    if request.method =='GET':
        return render(request,'booktest/upbook.html')
    else:
        try:
            aa = aaa.objects.get(title=request.POST['name'])

            aa.title = request.POST['xname']
            aa.save()
            return HttpResponseRedirect('/a1/list')
        except Exception as e:
            return HttpResponse('没有这本书')

def uphero(request,id):
    if request.method =='GET':

        bb = bbb.objects.get(pk=id)

        if bb.gender=='wan':
            cc = '男'
        else:
            cc = '女'


        return render(request, 'booktest/uphero.html', {'bb': bb,'cc':cc})
    elif request.method =='POST':

        bb = bbb.objects.get(pk=id)
        dd = bb.boot_id.id
        try:

            aa = aaa.objects.get(title=request.POST['book'])

            bb.boot_id = aa

        except Exception as e:
            pass

        bb.name = request.POST['heroname']

        if request.POST['gender'] != bb.gender:

            if request.POST['gender'] == '男':
                bb.gender = 'wan'
            elif request.POST['gender'] == '女':
                bb.gender = 'women'
            else:
                pass

        bb.skill = request.POST['skill']

        bb.save()

        return HttpResponseRedirect('/a1/xq/%s'%(dd))

a1/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>增加书籍</title>
</head>
<body>

    <div class="container">

        <form action="{% url 'booktest:addbook' %}" method="post">

            书名:<input type="text" name="bookname">
            <br>
            发布日期:<input type="datetime-local" name="time">
            <br>
            <input type="submit" name="提交">


        </form>



    </div>





</body>
</html>

a1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加</title>



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">



</head>
<body>

    <div class="container">

        <h2>添加角色</h2>
        <h3>书名:{{ book }}      ----{{ bookid }}</h3>
        <form action="{% url 'booktest:addhero' bookid %}" method="post">

        角色名字:<input type="text" name="username">
        <br>
        性别:<input type="radio" name="sex" value="man">男
            <input type="radio" name="sex" value="women">女
        <br>
        绝招:<input type="text" name="skill">
        <br>
        <input type="submit" name="提交">

        </form>


    </div>




</body>
</html>

a1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link rel="stylesheet" href="/static/css/aaa.css">

</head>
<body>
   <div id="id">
        <h2>这是列表页</h2>
        <br>
        {% if aa %}
            <ul>
                {% for i in aa %}
               {#  <li><a href="/a1/xq/{{ i.id }}">{{ i.title }}</a></li> #}
                <li><a href="{% url 'booktest:xq' i.id %}">{{ i.title }}</a>
                    <a href="{% url 'booktest:deletebook' i.id %}">删除</a>
                </li>

                {% empty %}
                没有书籍
                {% endfor %}
                <a href="{% url 'booktest:addbook' %}">添加书籍</a>
                <a href="{% url 'booktest:upbook' %}">更改书籍</a>
            </ul>
        {% else %}
        没有书籍
        {% endif %}

        <a href="{% url 'booktest:index' %}">去首页</a>
   </div>
</body>
</html>

a1/templates/booktest/shouye.html
<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <title>首页</title>



    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>


    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



    <link rel="stylesheet" href="/static/css/aaa.css">
</head>


<body>

    <div class="container">
        <h2>这是首页</h2>
        <a href="{% url 'booktest:list' %}">去列表</a>



        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>

      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">

        <div class="item active">
          <img src="/static/img/sucai/hot1.jpg" alt="...">
          <div class="carousel-caption">
          </div>

        </div>
        <div class="item">
          <img src="/static/img/sucai/hot2.jpg" alt="...">
          <div class="carousel-caption">
          </div>
        </div>

         <div class="item">
          <img src="/static/img/sucai/hot3.jpg" alt="...">
          <div class="carousel-caption">
          </div>
        </div>





      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>





    </div>


    <script>
        $('.carousel').carousel({
          interval: 1000
        })


    </script>


</body>
</html>

a1/templates/booktest/upbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>书籍更改</title>
</head>
<body>


    <div class="container">
        <form action="{% url 'booktest:upbook' %}" method="post">

            请输入书名:<input type="text" name="name" >
            <br>
            请输入要更改的东西<input type="text" name="xname">
            <br>
            <input type="submit" name="提交">



        </form>




    </div>



</body>
</html>

a1/templates/booktest/uphero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>更改英雄属性</title>
</head>
<body>


    <div class="container">
        {{ bb }}
        <form action="#" method="post">

            英雄名字:<input type="text" name="heroname" value="{{ bb.name }}">
            <br>

            性别:<input type="text" name="gender" value="{{ cc }}">
            <br>



            绝招:<input type="text" name="skill" value="{{ bb.skill }}">
            <br>
            书的名字:<input type="text" name="book" value="{{ bb.boot_id }}">
            <br>
            <input type="submit" name="提交">



        </form>



    </div>




</body>
</html>

a1/templates/booktest/xiangqing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>

    <link rel="stylesheet" href="/static/css/aaa.css">
</head>
<body>
   <div id="id">
        <h2>这是详情页</h2>
        <br>

        {% if bb %}

        <ul>
            <h3>{{ bb }}</h3>
            {% for i in bb.bbb_set.all %}
            <li>{{ i }}
            <a href="{% url 'booktest:deletehero' i.id %}">删除</a>
            <a href="{% url 'booktest:addhero' i.id %}">添加英雄</a>
            <a href="{% url 'booktest:uphero' i.id %}">更改英雄属性</a>
            </li>
            {% empty %}
            没有bb
            {% endfor %}
        </ul>
        {% else %}
        没有aa
        {% endif %}


        <a href="{% url 'booktest:list' %}">返回列表</a>
   </div>
</body>
</html>